let counryMap = {
    "韩国": "South Korea",
    "意大利": "Italy",
    "伊朗": "Iran",
    "德国": "Germany",
    "日本": "Japan",
    "法国": "France",
    "西班牙": "Spain",
    "美国": "United States of America",
    "英国": "United Kingdom",
    "瑞士": "Switzerland",
    "科威特": "Kuwait",
    "挪威": "Norway",
    "瑞典": "Sweden",
    "巴林": "Bahrain",
    "新加坡": "Singapore",
    "澳大利亚": "Australia",
    "伊拉克": "Iraq",
    "加拿大": "Canada",
    "马来西亚": "Malaysia",
    "印度": "India",
    "冰岛": "Iceland",
    "奥地利": "Austria",
    "荷兰": "Netherlands",
    "阿联酋": "United Arab Emirates",
    "比利时": "Belgium",
    "泰国": "Thailand",
    "丹麦": "Denmark",
    "以色列": "Israel",
    "黎巴嫩": "Lebanon",
    "阿曼": "Oman",
    "克罗地亚": "Croatia",
    "厄瓜多尔": "Ecuador",
    "圣马力诺": "San Marino",
    "希腊": "Greece",
    "阿尔及利亚": "Algeria",
    "卡塔尔": "Qatar",
    "芬兰": "Finland",
    "白俄罗斯": "Belarus",
    "巴基斯坦": "Pakistan",
    "罗马尼亚": "Romania",
    "墨西哥": "Mexico",
    "捷克": "Czech Republic",
    "葡萄牙": "Portugal",
    "塞内加尔": "Senegal",
    "巴西": "Brazil",
    "新西兰": "New Zealand",
    "阿塞拜疆": "Azerbaijan",
    "格鲁吉亚": "Georgia",
    "智利": "Chile",
    "爱尔兰": "Ireland",
    "印度尼西亚": "Indonesia",
    "沙特阿拉伯": "Saudi Arabia",
    "匈牙利": "Hungary",
    "俄罗斯": "Russia",
    "菲律宾": "Philippines",
    "埃及": "Egypt",
    "阿富汗": "Afghanistan",
    "爱沙尼亚": "Estonia",
    "北马其顿": "Macedonia",
    "尼日利亚": "Nigeria",
    "立陶宛": "Lithuania",
    "摩纳哥": "Monaco",
    "卢森堡": "Luxembourg",
    "亚美尼亚": "Armenia",
    "多米尼加": "Dominica",
    "安道尔": "Andorra",
    "乌克兰": "Ukraine",
    "摩洛哥": "Morocco",
    "约旦": "Jordan",
    "阿根廷": "Argentina",
    "列支敦士登": "Liechtenstein",
    "突尼斯": "Tunisia",
    "拉脱维亚": "Latvia",
    "波兰": "Poland",
    "斯洛文尼亚": "Slovenia",
    "越南": "Vietnam",
    "尼泊尔": "Nepal",
    "柬埔寨": "Cambodia",
    "斯里兰卡": "Sri Lanka",
    "中国": "China",
    "喀麦隆": "Cameroon",
    "波黑": "Bosnia and Herzegovina",
    "不丹": "Bhutan",
    "梵蒂冈": "Vatican",
    "塞尔维亚": "Republic of Serbia",
    "南非": "South Africa",
    "秘鲁": "Peru",
    "哥斯达黎加": "Costa Rica",
    "哥伦比亚": "Colombia",
    "多哥": "Togo"
}

export function countryNameDict(countryName) {
    let newCountryName = counryMap[countryName];
    if (newCountryName === undefined) {
        newCountryName = countryName;
    }
    return newCountryName;
}